# Generated by Django 4.2 on 2023-05-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField()),
                ('default_language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('c', 'C'), ('cpp', 'C++'), ('php', 'PHP'), ('ruby', 'Ruby')], max_length=50)),
            ],
        ),
    ]
